### ISSUE TITLE
Timepoint

### ISSUE THREAD

**Issue by cbohra00627** [Yeqzids/7timer-issues#15]
I am making a project on weather station. I want to use your API for that. But I am not able to understand what the word 'timepoint' describes exactly in the json document. Actually, when I search for a location by coordinates on the site, under the civil product... I am seeing: init at 5AM, and the data starts from 9 AM....
And when I download the json document for the same coordinates, it show different init, for examples:- 2021053100, I think this means 31/05/2021 and time - 00:00 AM, and according to the this the first timepoint in the dataseries is supposed to be referring to 3 AM, then 6 AM and so on...
But when I compare the temperature values on both the site and the json document.... the values for 9AM on the site and the 3AM on the json document are same... and the following values are also matching... SO, i dont know what is the correct time that the first timepoint is referring to in the json document...
I request you to look into this and provide me with an explanation...
Thank You!

**Comment by zouqiwu09** [comment]
I am not the developer but I think the init timepoint should be the GMT time. According to your description, I assume the input location is in timezone (GMT+6)?

**Comment by cbohra00627** [comment]
Yeah... I think you are right.
Thank You!
