### ISSUE TITLE
Using this for a demo

### ISSUE THREAD

**Issue by sayedihashimi** [Yeqzids/7timer-issues#18]
At the bottom of your webpage you mentioned for devs to let you know when they are planning to use your API. I wanted to let you know that I'm planning to use your API for a demo. Demo will happen on Tuesday next week at the Dev Intersections conference. My usage will not be that much, it's just a demo app to show weather for a selected city.

Thanks a lot for making this API available, it's working really great!

I didn't find any other contact method, so that is why I'm reaching out here.

**Comment by Yeqzids** [comment]
Hi Sayed -- whoops, sorry for noticing this so late. I'm very happy to hear that the API is useful and I hope the demo was a success! I should add my contact info to the website. Quanzhi
